all:
	make -C eprover
	make -C mizar
	make -C tptp
	make -C tstp
	make -C utils
	make -C vampire
	make -C ivy
	make -C prover9

clean:
	make -C eprover clean
	make -C mizar clean
	make -C tptp clean
	make -C tstp clean
	make -C utils clean
	make -C vampire clean
	make -C ivy clean
	make -C prover9 clean

check:
	# nothing to do yet
