all:
	make -C eprover
	make -C mizar
	make -C tptp
	make -C tstp
	make -C utils
	make -C vampire

clean:
	make -C eprover clean
	make -C mizar clean
	make -C tptp clean
	make -C tstp clean
	make -C utils clean
	make -C vampire clean
